### ISSUE TITLE
Trouble with FetchContent

### ISSUE THREAD

**Issue by chrhaase** [sudara/melatonin_inspector#60]
Hi and thanks for this great piece of work! Very helpful :)

I went the FetchContent way when adding this to my project, but got an error at [this line](https://github.com/sudara/melatonin_inspector/blob/4e353bdd7664f4cec2967b980548d976f4aeea4b/CMakeLists.txt#L15), because FetchContent will by default add a "-src" suffix to the name of the directory.

I could resolve this by adding a specific directory name like this:
```cmake
include (FetchContent)

FetchContent_Declare (melatonin_inspector
  GIT_REPOSITORY https://github.com/sudara/melatonin_inspector.git
  GIT_TAG origin/main
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/melatonin_inspector)

FetchContent_MakeAvailable (melatonin_inspector)

target_link_libraries (yourTarget PRIVATE Melatonin::Inspector)
```

My apologies if this is somehow specific to my project!

**Comment by sudara** [comment]
Hey @chrhaase! Glad you could try it out! Please feel free to open issues with random features/thoughts, etc, I'm like 100% on this project at the moment :) 

Sorry you had install trouble. I see the problem. I guess that's why we stuck the module files in a redundant folder for my other cmake friendly module `[melatonin_perfetto](https://github.com/sudara/melatonin_perfetto)`

I think I'll steal your solution for now and update the README so I don't have to bury the module code. Thank you!

**Comment by chrhaase** [comment]
Yes, I was just about to suggest a module folder hehe. That would also potentially help folks naming the submodule folder something else.

> Hey @chrhaase! Glad you could try it out! Please feel free to open issues with random features/thoughts, etc, I'm like 100% on this project at the moment :)

And great, I will! :)
